// a list of all possible locations in search page
export const locations = [
    ["London, UK", "London_GB"],
    ["Manchester, UK", "Manchester_GB"],
    ["Birmingham, UK", "Birmingham_GB"],
    ["Bristol, UK", "Bristol_GB"],
    ["Wolverhampton, UK", "Wolverhampton_GB"],
    ["Leeds, UK", "Leeds_GB"],
    ["Bradford, UK", "Bradford_GB"],
    ["Glasgow, UK", "Glasgow_GB"],
    ["Southampton, UK", "Southampton_GB"],
    ["Portsmouth, UK", "Portsmouth_GB"],
    ["Liverpool, UK", "Liverpool_GB"],
    ["Newcastle, UK", "Newcastle_GB"],
    ["Nottingham, UK", "Nottingham_GB"],
    ["Sheffield, UK", "Sheffield_GB"],
    ["Belfast, UK", "Belfast_GB"],
    ["Leicester, UK", "Leicester_GB"],
    ["Edinburgh, UK", "Edinburgh_GB"],
    ["Dublin, Ireland", "Dublin_IE"],
    ["Cork, Ireland", "Cork_IE"],
    ["Belfast, Ireland", "Belfast_IE"],
    ["Paris, France", "Paris_FR"],
    ["Marseille, France", "Marseille_FR"],
    ["Lyon, France", "Lyon_FR"],
    ["Toulouse, France", "Toulouse_FR"],
    ["Nice, France", "Nice_FR"],
    ["Nantes, France", "Nantes_FR"],
    ["Montpellier, France", "Montpellier_FR"],
    ["Bordeaux, France", "Bordeaux_FR"],
    ["Madrid, Spain", "Madrid_ES"],
    ["Barcelona, Spain", "Barcelona_ES"],
    ["Valencia, Spain", "Valencia_ES"],
    ["Seville, Spain", "Seville_ES"],
    ["Malaga, Spain", "Malaga_ES"],
    ["Granada, Spain", "Granada_ES"],
    ["Cordoba, Spain", "Cordoba_ES"],
    ["Rome, Italy", "Rome_IT"],
    ["Milan, Italy", "Milan_IT"],
    ["Naples, Italy", "Naples_IT"],
    ["Turin, Italy", "Turin_IT"],
    ["Florence, Italy", "Florence_IT"],
    ["Venice, Italy", "Venice_IT"],
    ["Bologna, Italy", "Bologna_IT"],
    ["Lisbon, Portugal", "Lisbon_PT"],
    ["Porto, Portugal", "Porto_PT"],
    ["Athens, Greece", "Athens_GR"],
    ["Thessaloniki, Greece", "Thessaloniki_GR"],
    ["Berlin, Germany", "Berlin_DE"],
    ["Munich, Germany", "Munich_DE"],
    ["Hamburg, Germany", "Hamburg_DE"],
    ["Frankfurt, Germany", "Frankfurt_DE"],
    ["Leipzig, Germany", "Leipzig_DE"],
    ["Cologne, Germany", "Cologne_DE"],
    ["Sydney, Australia", "Sydney_AU"],
    ["Melborne, Australia", "Melborne_AU"],
    ["Canberra, Australia", "Canberra_AU"],
    ["Adelaide, Australia", "Adelaide_AU"],
    ["Perth, Australia", "Perth_AU"],
    ["Brisbane, Australia", "Brisbane_AU"],
    ["Istanbul, Turkey", "Istanbul_TR"],
    ["Ankara, Turkey", "Ankara_TR"],
    ["Antalya, Turkey", "Antalya_TR"],
    ["Bursa, Turkey", "Bursa_TR"],
    ["Toronto, Canada", "Toronto_CA"],
    ["Montreal, Canada", "Montreal_CA"],
    ["Winnipeg, Canada", "Winnipeg_CA"],
    ["Quebec City, Canada", "QuebecCity_CA"],
    ["Vancouver, Canada", "Vancouver_CA"],
    ["Ottawa, Canada", "Ottawa_CA"],
    ["New York, United States", "NewYork_US"],
    ["Chicago, United States", "Chicago_US"],
    ["San Diego, United States", "SanDiego_US"],
    ["San Fransico, United States", "SanFransico_US"],
    ["Washington DC, United States", "WashingtonDC_US"],
    ["Los Angeles, United States", "LosAngeles_US"],
    ["Boston, United States", "Boston_US"],
    ["Marrakesh, Morocco", "Marrakesh_MA"],
    ["Fes, Morocco", "Fes_MA"],
    ["Tangier, Morocco", "Tangier_MA"],
    ["Rabat, Morocco", "Rabat_MA"],
    ["Cassablanca, Morocco", "Cassablanca_MA"],
];

